# Generated by Django 2.0.4 on 2018-05-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
